# Generated by Django 5.2.4 on 2025-07-29 19:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scan_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reminder",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="reminder",
            name="completion_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="reminder",
            name="duration",
            field=models.CharField(
                choices=[
                    ("ongoing", "Ongoing"),
                    ("1_week", "1 Week"),
                    ("2_weeks", "2 Weeks"),
                    ("1_month", "1 Month"),
                    ("3_months", "3 Months"),
                    ("6_months", "6 Months"),
                    ("custom", "Custom duration"),
                ],
                default="ongoing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reminder",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("once", "Once a day"),
                    ("twice", "Twice a day"),
                    ("thrice", "Three times a day"),
                    ("four", "Four times a day"),
                    ("custom", "Custom frequency"),
                ],
                default="once",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reminder",
            name="last_taken",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reminder",
            name="next_reminder",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reminder",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reminder",
            name="notification_sound",
            field=models.CharField(default="default", max_length=50),
        ),
        migrations.AddField(
            model_name="reminder",
            name="reminder_times",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="reminder",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="reminder",
            name="times_taken",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reminder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="schedule",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="HealthInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insight_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("priority", models.CharField(default="medium", max_length=20)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicineInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine1", models.CharField(max_length=255)),
                ("medicine2", models.CharField(max_length=255)),
                ("interaction_type", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("severity_level", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("medicine1", "medicine2")},
            },
        ),
        migrations.CreateModel(
            name="MedicineScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="medicine_scans/")),
                ("medicine_name", models.CharField(blank=True, max_length=255)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("medicine_info", models.JSONField(blank=True, default=dict)),
                ("is_favorite", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("email_reminders", models.BooleanField(default=True)),
                ("sms_reminders", models.BooleanField(default=False)),
                ("reminder_sound", models.CharField(default="default", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ScanHistory",
        ),
    ]
